server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        # 这是在seata的file.conf中配置的事务组ID
        tx-service-group: txl_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: wuwenqin

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  # 扫描类路径下mapper文件夹下的.xml配置文件
  mapper-locations: classpath:mapper/*.xml
