server:
  port: 80

eureka:
  client:
    # 表示不将其注入Eureka作为微服务，不作为Eureak客户端了，而是作为Feign客户端
    register-with-eureka: false
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

    # 设置feign客户端超时时间   ，默认为1s
ribbon:
      # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所有的时间
  ReadTimeout: 5000
      # 建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

    # 开启日志的
logging:
  level:
    # feign日志以什么级别监控那个接口
    com.awu.springcloud.service.PaymentFeignService: debug
